import type { Metadata } from 'next';
import '@/lib/styles/globals.css';
import LocalFont from 'next/font/local';
import SessionProviderComponent from '@/components/wrapper/session';
import { getServerSession } from 'next-auth';
import AuthOptions from '@/lib/utils/auth';
import EnvProviderComponent from '@/components/wrapper/env';
import validEnv from '@/lib/utils/env';
import NextTopLoader from 'nextjs-toploader';
import dynamic from 'next/dynamic';

const ScrollTopButton = dynamic(() => import('@/components/button/scrollTop'), {
  ssr: false,
});

const DrawerComponent = dynamic(() => import('@/components/client/drawer'), {
  ssr: false,
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const font = LocalFont({
  src: '../lib/fonts/open_sans.ttf',
  display: 'swap',
  adjustFontFallback: 'Arial',
});

const RootLayout = async ({ children }: { children: React.ReactNode }) => {
  const session = await getServerSession(AuthOptions);
  return (
    <html lang="en">
      <body className={font.className}>
        <SessionProviderComponent session={session}>
          <EnvProviderComponent env={validEnv}>
            <NextTopLoader
              color="#018c01"
              crawl
              showSpinner={false}
              height={4}
            />
            {children}
            <ScrollTopButton />
            <DrawerComponent />
          </EnvProviderComponent>
        </SessionProviderComponent>
      </body>
    </html>
  );
};

export default RootLayout;
